services:
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "3001:3001"
    environment:
      - APP_NAME=USER_SERVICE
    networks:
      - main-net
    restart: unless-stopped
  
  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "3000:3000"
    environment:
      - APP_NAME=PRODUCT_SERVICE
    networks:
      - main-net
    restart: unless-stopped

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "3002:3002"
    environment:
      - APP_NAME=ORDER_SERVICE
      - USER_SERVICE_BASE_URL=http://user-service:3001
      - PRODUCT_SERVICE_BASE_URL=http://product-service:3000
    networks:
      - main-net
    restart: unless-stopped
    depends_on:
      - user-service
      - product-service
  
networks:
  main-net:
    driver: bridge
