name: Build and push images to ECR

on:
  push:
    branches:
      - master

env:
  AWS_REGION: us-east-1
  ECS_CLUSTER: cluster
  ECS_SERVICE: ecs_service

jobs:
  build:
    name: Build images
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      
      - name: Build & Push Docker images
        id: docker-build
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_USER_SERVICE_REPOSITORY: user_service
          ECR_PRODUCT_SERVICE_REPOSITORY: product_service
          ECR_ORDER_SERVICE_REPOSITORY: order_service
        run: |
          # Build Docker images
          cd ./user-service && docker build -t $ECR_REGISTRY/$ECR_USER_SERVICE_REPOSITORY:latest .
          cd ../product-service && docker build -t $ECR_REGISTRY/$ECR_PRODUCT_SERVICE_REPOSITORY:latest .
          cd ../order-service && docker build -t $ECR_REGISTRY/$ECR_ORDER_SERVICE_REPOSITORY:latest .

          # Push Docker image tags
          docker push $ECR_REGISTRY/$ECR_USER_SERVICE_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_PRODUCT_SERVICE_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_ORDER_SERVICE_REPOSITORY:latest
      
      - name: Deploy to AWS ECS
        run: |
          aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --force-new-deployment